spring:
  profiles:
    active: dev
---
server:
  port: 7201
spring:
  profiles: dev
  application:
    name: ms5-scconfig-client-dev
---
server:
  port: 7202
spring:
  profiles: pro
  application:
    name: ms5-scconfig-client-pro
---
server:
  port: 7204
spring:
  profiles: hadev
  application:
    name: ms5-scconfig-client-ha
