spring:
  profiles:
    active: dev
---
server:
  port: 7203
spring:
  profiles: dev
  application:
    name: ms5-scconfig-client-manualrefresh-dev
---
server:
  port: 7203
spring:
  profiles: pro
  application:
    name: ms5-scconfig-client-manualrefresh-pro
