spring:
  profiles:
    active: dev
---
server:
  port: 7203
security:
  basic:
    enabled: true
  user:
    name: manualrefresh
    password: dev123
spring:
  profiles: dev
  application:
    name: ms5-scconfig-client-manualrefresh-dev
---
server:
  port: 7203
security:
  basic:
    enabled: true
  user:
    name: eurekapro
    password: pro123
spring:
  profiles: pro
  application:
    name: ms5-scconfig-client-manualrefresh-propro
